databases:
  - name: Zultech_main_db
    plan: free
    databaseName: Zultech_main_db
    user: Zultech_main_db

services:
  - type: web
    plan: free
    name: Zultech_main
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn Zultech_main.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Zultech_main_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False